# Generated by Django 6.0.1 on 2026-01-17 08:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_codingchallenge_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('coding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='coding.codingchallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodingSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_text', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('coding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='coding.codingchallenge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=20)),
                ('coding_challenges', models.ManyToManyField(related_name='bookmarked_by', to='coding.codingchallenge')),
            ],
        ),
    ]
